### PR TITLE
update list of relevent DMSR [[sub]sub]sections

### PR DESCRIPTION
**Pull request by jhoblitt**
Note that "Timely Publication of Level 2 Data Releases" has been deleted
from the DMSR.

### CODE REVIEW

**Comment by jhoblitt** [comment]
Are there any other sections of the DMSR that should be considered relevant for network verification?

**Review by leannep — APPROVED** [review]

**Comment by leannep** [comment]
> other

**Comment by leannep** [comment]
1.6.4  Constraints on Level 1 Special Program Products Generation, ID: DMS-REQ-0344 (Priority: 2)
and 
2.2.7 DIASource Precovery, ID: DMS-REQ-0287 (Priority: 1b)
are subject to the same constraints as 1.3.1 and 2.2.9 in terms of the OTT1 and/or  L1PublicT requirement

You list 2.2.3, will this comprise the sub-requirements 2.2.3.2 Alert Delay and Failure Tolerances
ID: DMS-REQ-0392 (Priority: 2) and 2.2.3.1 Alert Stream Distribution
ID: DMS-REQ-0391 (Priority: 2) ? Bothe of these are constrained by L1PublicT and OTT1. Might be good t inculde them explicitly

Additionally
4.1.2 Engineering & Facility Database Archive, ID: DMS-REQ-0102 (Priority: 1a)
also needs to have updated information available within  L1PublicT

**Comment by jhoblitt** [comment]
I have converted the list of DMSR sections into a table of individual requirement names & IDs. I have added all of the subsection/requirements listed by @leannep . However, I'm unsure if `2.2.3.1/DMS-REQ-0392` should fall into the scope of this document.  That is a requirement that applies to the alerts stream sent out from the USDF and does not involve the the summit, base, or long haul network.  Should we update the scope section to explicitly state that this document is summit, base, summit<->base, and *<->USDF only? Or should USDF requirements also be part of this doc?

**Comment by jhoblitt** [comment]
I have added a simple figure showing the data transfers in LSE-61 and some words to the scope section attempting to exclude data transfers from the USDF to alert brokers, DACs, processing partners, etc.

**Comment by jhoblitt** [comment]
I'm going to merge this as-is but fully expect additional changes.

**Pull request merged**
